# Generated by Django 3.1.2 on 2020-10-24 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20201021_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='chapter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutorial.chapter'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='displayName',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
